# maxcommands - the maximum number of commands per book
# chatenabled - whether or not people can print chat from a book
# commandsenabled - whether or not people can use commands from a book
# bookname - the name a book should have to be recognized as a command book
# enabledispensers: whether or not dispensers can execute commands
# doconsolebooks: whether or not dispensers can make console execute command. This should stay false, except for special cases.
# disabledcommands - a list of commands. These commands will not be run in books.
# selectors: whether or not to enable selectors (@a, @p, @r)
# [WARNING!] DO NOT DELETE THIS LINE: '- macro' OR YOUR SERVER WILL POSSIBLY CRASH

maxcommands: 16
chatenabled: true
commandsenabled: true
bookname: 'command'
enabledispensers: true
doconsolebooks: false
selectors: true
disabledcommands:
- macro
- ban
- kill
- kick
